### Project specific config ###
language: generic

env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    # Disable automatic beta channel tests until build is fixed: https://github.com/atom/atom/issues/14061
    # - ATOM_CHANNEL=beta

os:
  - linux
  - osx

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh
  - './node_modules/.bin/flow'

# Needed to disable the auto-install step running `npm install`
install: true

notifications:
  email: false

# branches:
#   only:
#     - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
  code_climate:
    repo_token: 87dc83c7f5b2b14f1d4ab2a155bcd69d2c097c4828e811027327705a6b1cd1a6
