### Project specific config ###
environment:
  APM_TEST_PACKAGES:
  ATOM_LINT_WITH_BUNDLED_NODE: "true"

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

### Generic setup follows ###
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/viddo/711fcf2b9ebcc4a717da284fad4d5a38/raw/09fde224d3720a20e9b8df4c53357b2e6b323e07/build-package.ps1'))

version: "{build}"
platform: x64
clone_depth: 10
skip_tags: true
test: off
deploy: off
